modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "miningutility"
version = "${version}"
displayName = "Mining Utility"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""
[[mixins]]
    config = "miningutility.mixins.json"
[[dependencies.miningutility]]
    modId = "architectury"
    type = "required"
    versionRange = "[13,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.miningutility]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.miningutility]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "BOTH"